# Outlier Analysis

## Objective

Identify, analyze, and handle potential outliers in the Titanic dataset.

In [0]:
import pandas as pd
import numpy as np

## 1. Load the Dataset

Load the Titanic dataset into a Pandas DataFrame.

In [0]:
df = pd.read_csv("/Volumes/workspace/default/ml_data/Titanic-Dataset.csv")

## 2. Understand Outliers

Identify values that are unusually far from most other values in a dataset.

An outlier is not automatically an error and should be investigated before removal or modification.

## 3. Calculate Q1 and Q3

Calculate the first quartile (Q1) and third quartile (Q3) of passenger ages.

In [0]:
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

print("Q1:", Q1)
print("Q3:", Q3)

Q1: 20.125
Q3: 38.0

## 4. Interquartile Range (IQR)
### FORMULA
IQR = Q3 - Q1

In [0]:
IQR = Q3 - Q1

print("IQR:", IQR)

IQR: 17.875

## 5. Calculate Outlier Boundaries

Calculate the lower and upper boundaries using the IQR method.

###Formula
Lower Bound = Q1 - 1.5 × IQR, 
Upper Bound = Q3 + 1.5 × IQR

In [0]:
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower Bound:", lower)
print("Upper Bound:", upper)

Lower Bound: -6.6875
Upper Bound: 64.8125

## 6. Identify Potential Outliers

Identify passenger ages that fall outside the IQR boundaries.

In [0]:
outliers = df[(df["Age"]>upper) | (df["Age"] < lower)]
outliers[["Name", "Age"]]

                                     Name   Age
33                  Wheadon, Mr. Edward H  66.0
54         Ostby, Mr. Engelhart Cornelius  65.0
96              Goldschmidt, Mr. George B  71.0
116                  Connors, Mr. Patrick  70.5
280                      Duane, Mr. Frank  65.0
456             Millet, Mr. Francis Davis  65.0
493               Artagaveytia, Mr. Ramon  71.0
630  Barkworth, Mr. Algernon Henry Wilson  80.0
672           Mitchell, Mr. Henry Michael  70.0
745          Crosby, Capt. Edward Gifford  70.0
851                   Svensson, Mr. Johan  74.0

## 7. Inspect Potential Outliers

Inspect the passenger details associated with the potential outliers.

In [0]:
outliers[["Name","Age","Sex","Pclass","Fare"]]

                                     Name   Age   Sex  Pclass     Fare
33                  Wheadon, Mr. Edward H  66.0  male       2  10.5000
54         Ostby, Mr. Engelhart Cornelius  65.0  male       1  61.9792
96              Goldschmidt, Mr. George B  71.0  male       1  34.6542
116                  Connors, Mr. Patrick  70.5  male       3   7.7500
280                      Duane, Mr. Frank  65.0  male       3   7.7500
456             Millet, Mr. Francis Davis  65.0  male       1  26.5500
493               Artagaveytia, Mr. Ramon  71.0  male       1  49.5042
630  Barkworth, Mr. Algernon Henry Wilson  80.0  male       1  30.0000
672           Mitchell, Mr. Henry Michael  70.0  male       2  10.5000
745          Crosby, Capt. Edward Gifford  70.0  male       1  71.0000
851                   Svensson, Mr. Johan  74.0  male       3   7.7750

## 8. Evaluate Potential Outliers

Determine whether the identified outliers represent valid observations or possible data errors.

Valid unusual values should be retained unless there is evidence that they are incorrect.

### Observation

The identified older ages are plausible passenger ages rather than obvious data errors. Retain these observations for further analysis.

## 9. Remove Outliers

Remove observations that fall outside the IQR boundaries when there is a valid reason to exclude them.

In [0]:
clean_data = df[(df["Age"] >= lower) & (df["Age"] <= upper)]

clean_data[["Name", "Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
885               Rice, Mrs. William (Margaret Norton)  39.0
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[703 rows x 2 columns]

## 10. Replace Outliers

Replace outlier values with the median when there is a valid reason to reduce the effect of extreme values.

In [0]:
median_age = df["Age"].median()

replaced_data = df.copy()
replaced_data.loc[replaced_data["Age"] > upper, "Age"] = median_age

replaced_data[["Name", "Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

## 11. Cap Outliers

Cap values outside the IQR boundaries at the corresponding lower or upper boundary.

In [0]:
capped_data = df["Age"].clip(lower=lower, upper=upper)

capped_data

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

## 12. Transform the Data

Apply a logarithmic transformation to reduce the influence of large values.
np.log1p(x) calculates log(1 + x) and safely handles zero values.

In [0]:
log_data = np.log1p(df["Age"])

log_data

0      3.135494
1      3.663562
2      3.295837
3      3.583519
4      3.583519
         ...
886    3.332205
887    2.995732
888         NaN
889    3.295837
890    3.496508
Name: Age, Length: 891, dtype: float64