# 12 — Prediction

## Objective

Use the trained Logistic Regression model to predict survival for individual passenger records and inspect the associated class probabilities.

In [0]:
df = spark.table("default.titanic_encoded").toPandas()

X = df.drop(columns= ["PassengerId", "Name", "Ticket", "Cabin", "Survived"])
y = df["Survived"]

X.shape, y.shape

((891, 33), (891,))

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

model =LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [0]:
X.columns.tolist()

['Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'FamilySize',
 'IsAlone',
 'Embarked_C',
 'Embarked_Q',
 'Embarked_S',
 'Title_Master',
 'Title_Miss',
 'Title_Mr',
 'Title_Mrs',
 'Title_Other',
 'AgeGroup_Child',
 'AgeGroup_Teen',
 'AgeGroup_Adult',
 'AgeGroup_Senior',
 'FamilySizeGroup_Alone',
 'FamilySizeGroup_Small',
 'FamilySizeGroup_Medium',
 'FamilySizeGroup_Large',
 'Cabin_Deck_A',
 'Cabin_Deck_B',
 'Cabin_Deck_C',
 'Cabin_Deck_D',
 'Cabin_Deck_E',
 'Cabin_Deck_F',
 'Cabin_Deck_G',
 'Cabin_Deck_T',
 'Cabin_Deck_Unknown']

#FIRST PASSENGER :#

In [0]:
new_passenger = {
    "Pclass" : 1,
    "Sex" : "female",
    "Age" : 25,
    "SibSp" : 0,
    "Parch" : 0,
    "Fare" : 80,
    "Embarked" : "C",
    "Title" : "Miss",
    "Cabin_Deck" : "Unknown"
}

new_passenger

{'Pclass': 1,
 'Sex': 'female',
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown'}

In [0]:
new_passenger["FamilySize"] = (
    new_passenger["SibSp"] +
    new_passenger["Parch"] +
    1
)

new_passenger

{'Pclass': 1,
 'Sex': 'female',
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 1}

In [0]:
new_passenger["IsAlone"] = int(new_passenger["FamilySize"] == 1)
new_passenger

{'Pclass': 1,
 'Sex': 'female',
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 1,
 'IsAlone': 1}

In [0]:
new_passenger["Age"] = 25
age = new_passenger["Age"]

if age <= 12:
    new_passenger["AgeGroup"] = "Child"
elif age <=17:
    new_passenger["AgeGroup"] = "Teen"
elif age <50:
    new_passenger["AgeGroup"] = "Adult"
else:
    new_passenger["AgeGroup"] = "Senior"
new_passenger

{'Pclass': 1,
 'Sex': 'female',
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 1,
 'IsAlone': 1,
 'AgeGroup': 'Adult'}

In [0]:
family_size = new_passenger["FamilySize"]

if family_size == 1:
    new_passenger["FamilySizeGroup"] = "Alone"
elif family_size <= 4:
    new_passenger["FamilySizeGroup"] = "Small"
elif family_size <= 6:
    new_passenger["FamilySizeGroup"] = "Medium"
else:
    new_passenger["FamilySizeGroup"] = "Large"

new_passenger

{'Pclass': 1,
 'Sex': 'female',
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 1,
 'IsAlone': 1,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Alone'}

In [0]:
new_passenger["Sex"] = {"male" : 0, "female" : 1}[new_passenger["Sex"]]

new_passenger

{'Pclass': 1,
 'Sex': 1,
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 1,
 'IsAlone': 1,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Alone'}

In [0]:
new_passenger["Embarked_C"] = int(new_passenger["Embarked"] == "C")
new_passenger["Embarked_Q"] = int(new_passenger["Embarked"] == "Q")
new_passenger["Embarked_S"] = int(new_passenger["Embarked"] == "S")

new_passenger

{'Pclass': 1,
 'Sex': 1,
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 1,
 'IsAlone': 1,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Alone',
 'Embarked_C': 1,
 'Embarked_Q': 0,
 'Embarked_S': 0}

In [0]:
new_passenger["Title_Master"] = int(new_passenger["Title"] == "Master")
new_passenger["Title_Miss"] = int(new_passenger["Title"] == "Miss")
new_passenger["Title_Mr"] = int(new_passenger["Title"] == "Mr")
new_passenger["Title_Mrs"] = int(new_passenger["Title"] == "Mrs")
new_passenger["Title_Other"] = int(
    new_passenger["Title"] == "Other"
)

new_passenger

{'Pclass': 1,
 'Sex': 1,
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 1,
 'IsAlone': 1,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Alone',
 'Embarked_C': 1,
 'Embarked_Q': 0,
 'Embarked_S': 0,
 'Title_Master': 0,
 'Title_Miss': 1,
 'Title_Mr': 0,
 'Title_Mrs': 0,
 'Title_Other': 0}

In [0]:
new_passenger["AgeGroup_Child"] = int(new_passenger["AgeGroup"] == "Child")
new_passenger["AgeGroup_Teen"] = int(new_passenger["AgeGroup"] == "Teen")
new_passenger["AgeGroup_Adult"] = int(new_passenger["AgeGroup"] == "Adult")
new_passenger["AgeGroup_Senior"] = int(new_passenger["AgeGroup"] == "Senior")

new_passenger

{'Pclass': 1,
 'Sex': 1,
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 1,
 'IsAlone': 1,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Alone',
 'Embarked_C': 1,
 'Embarked_Q': 0,
 'Embarked_S': 0,
 'Title_Master': 0,
 'Title_Miss': 1,
 'Title_Mr': 0,
 'Title_Mrs': 0,
 'Title_Other': 0,
 'AgeGroup_Child': 0,
 'AgeGroup_Teen': 0,
 'AgeGroup_Adult': 1,
 'AgeGroup_Senior': 0}

In [0]:
new_passenger["FamilySizeGroup_Alone"] = int(
    new_passenger["FamilySizeGroup"] == "Alone"
)

new_passenger["FamilySizeGroup_Small"] = int(
    new_passenger["FamilySizeGroup"] == "Small"
)

new_passenger["FamilySizeGroup_Medium"] = int(
    new_passenger["FamilySizeGroup"] == "Medium"
)

new_passenger["FamilySizeGroup_Large"] = int(
    new_passenger["FamilySizeGroup"] == "Large"
)

new_passenger

{'Pclass': 1,
 'Sex': 1,
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 1,
 'IsAlone': 1,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Alone',
 'Embarked_C': 1,
 'Embarked_Q': 0,
 'Embarked_S': 0,
 'Title_Master': 0,
 'Title_Miss': 1,
 'Title_Mr': 0,
 'Title_Mrs': 0,
 'Title_Other': 0,
 'AgeGroup_Child': 0,
 'AgeGroup_Teen': 0,
 'AgeGroup_Adult': 1,
 'AgeGroup_Senior': 0,
 'FamilySizeGroup_Alone': 1,
 'FamilySizeGroup_Small': 0,
 'FamilySizeGroup_Medium': 0,
 'FamilySizeGroup_Large': 0}

In [0]:
cabin_decks = ["A", "B", "C", "D", "E", "F", "G", "T", "Unknown"]

for deck in cabin_decks:
    new_passenger[f"Cabin_Deck_{deck}"] = int(
        new_passenger["Cabin_Deck"] == deck
    )

new_passenger

{'Pclass': 1,
 'Sex': 1,
 'Age': 25,
 'SibSp': 0,
 'Parch': 0,
 'Fare': 80,
 'Embarked': 'C',
 'Title': 'Miss',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 1,
 'IsAlone': 1,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Alone',
 'Embarked_C': 1,
 'Embarked_Q': 0,
 'Embarked_S': 0,
 'Title_Master': 0,
 'Title_Miss': 1,
 'Title_Mr': 0,
 'Title_Mrs': 0,
 'Title_Other': 0,
 'AgeGroup_Child': 0,
 'AgeGroup_Teen': 0,
 'AgeGroup_Adult': 1,
 'AgeGroup_Senior': 0,
 'FamilySizeGroup_Alone': 1,
 'FamilySizeGroup_Small': 0,
 'FamilySizeGroup_Medium': 0,
 'FamilySizeGroup_Large': 0,
 'Cabin_Deck_A': 0,
 'Cabin_Deck_B': 0,
 'Cabin_Deck_C': 0,
 'Cabin_Deck_D': 0,
 'Cabin_Deck_E': 0,
 'Cabin_Deck_F': 0,
 'Cabin_Deck_G': 0,
 'Cabin_Deck_T': 0,
 'Cabin_Deck_Unknown': 1}

In [0]:
import pandas as pd
new_passenger_df = pd.DataFrame([new_passenger])
new_passenger_df

   Pclass  Sex  Age  ...  Cabin_Deck_G  Cabin_Deck_T  Cabin_Deck_Unknown
0       1    1   25  ...             0             0                   1

[1 rows x 38 columns]

In [0]:
new_passenger_df = new_passenger_df[X.columns]
new_passenger_df

   Pclass  Sex  Age  ...  Cabin_Deck_G  Cabin_Deck_T  Cabin_Deck_Unknown
0       1    1   25  ...             0             0                   1

[1 rows x 33 columns]

In [0]:
new_passenger_df.shape

(1, 33)

In [0]:
new_passenger_df.columns.tolist()

['Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'FamilySize',
 'IsAlone',
 'Embarked_C',
 'Embarked_Q',
 'Embarked_S',
 'Title_Master',
 'Title_Miss',
 'Title_Mr',
 'Title_Mrs',
 'Title_Other',
 'AgeGroup_Child',
 'AgeGroup_Teen',
 'AgeGroup_Adult',
 'AgeGroup_Senior',
 'FamilySizeGroup_Alone',
 'FamilySizeGroup_Small',
 'FamilySizeGroup_Medium',
 'FamilySizeGroup_Large',
 'Cabin_Deck_A',
 'Cabin_Deck_B',
 'Cabin_Deck_C',
 'Cabin_Deck_D',
 'Cabin_Deck_E',
 'Cabin_Deck_F',
 'Cabin_Deck_G',
 'Cabin_Deck_T',
 'Cabin_Deck_Unknown']

In [0]:
prediction = model.predict(new_passenger_df)
prediction

array([1])

In [0]:
probability = model.predict_proba(new_passenger_df)
probability

array([[0.07914946, 0.92085054]])

#SECOND PASSENGER :#

In [0]:
second_passenger = {
    "Pclass" : 3,
    "Sex" : "male",
    "Age" : 30,
    "SibSp" : 1,
    "Parch" : 0,
    "Fare" : 15,
    "Embarked" : "S",
    "Title" : "Mr",
    "Cabin_Deck" : "Unknown"
}

In [0]:
second_passenger["FamilySize"] = (
    second_passenger["SibSp"] +
    second_passenger["Parch"] + 1
)
second_passenger

{'Pclass': 3,
 'Sex': 'male',
 'Age': 30,
 'SibSp': 1,
 'Parch': 0,
 'Fare': 15,
 'Embarked': 'S',
 'Title': 'Mr',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 2}

In [0]:
second_passenger["IsAlone"] = int(second_passenger["FamilySize"]==1)
second_passenger

{'Pclass': 3,
 'Sex': 'male',
 'Age': 30,
 'SibSp': 1,
 'Parch': 0,
 'Fare': 15,
 'Embarked': 'S',
 'Title': 'Mr',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 2,
 'IsAlone': 0}

In [0]:
age = second_passenger["Age"]

if age <= 12:
    second_passenger["AgeGroup"] = "Child"
elif age <=17:
    second_passenger["AgeGroup"] = "Teen"
elif age <=59:
    second_passenger["AgeGroup"] = "Adult"
else:
    second_passenger["AgeGroup"] = "Senior"

second_passenger

{'Pclass': 3,
 'Sex': 'male',
 'Age': 30,
 'SibSp': 1,
 'Parch': 0,
 'Fare': 15,
 'Embarked': 'S',
 'Title': 'Mr',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 2,
 'IsAlone': 0,
 'AgeGroup': 'Adult'}

In [0]:
familysize = second_passenger["FamilySize"]

if familysize == 1:
    second_passenger["FamilySizeGroup"] = "Alone"
elif familysize <=4:
    second_passenger["FamilySizeGroup"] = "Small"
elif familysize <=6:
    second_passenger["FamilySizeGroup"] = "Medium"
else:
    second_passenger["FamilySizeGroup"] = "Large"

second_passenger

{'Pclass': 3,
 'Sex': 'male',
 'Age': 30,
 'SibSp': 1,
 'Parch': 0,
 'Fare': 15,
 'Embarked': 'S',
 'Title': 'Mr',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 2,
 'IsAlone': 0,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Small'}

In [0]:
second_passenger["Sex"] = {"male" : 0, "female" : 1}[second_passenger["Sex"]]

second_passenger

{'Pclass': 3,
 'Sex': 0,
 'Age': 30,
 'SibSp': 1,
 'Parch': 0,
 'Fare': 15,
 'Embarked': 'S',
 'Title': 'Mr',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 2,
 'IsAlone': 0,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Small'}

In [0]:
second_passenger["Embarked_C"] = int(second_passenger["Embarked"] =="C")
second_passenger["Embarked_Q"] = int(second_passenger["Embarked"] =="Q")
second_passenger["Embarked_S"] = int(second_passenger["Embarked"] =="S")

second_passenger

{'Pclass': 3,
 'Sex': 0,
 'Age': 30,
 'SibSp': 1,
 'Parch': 0,
 'Fare': 15,
 'Embarked': 'S',
 'Title': 'Mr',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 2,
 'IsAlone': 0,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Small',
 'Embarked_C': 0,
 'Embarked_Q': 0,
 'Embarked_S': 1}

In [0]:
second_passenger["Title_Master"] = int(second_passenger["Title"]== "Master")
second_passenger["Title_Miss"] = int(second_passenger["Title"]== "Miss")
second_passenger["Title_Mr"] = int(second_passenger["Title"]== "Mr")
second_passenger["Title_Mrs"] = int(second_passenger["Title"]== "Mrs")
second_passenger["Title_Other"] = int(second_passenger["Title"]== "Other")

second_passenger

{'Pclass': 3,
 'Sex': 0,
 'Age': 30,
 'SibSp': 1,
 'Parch': 0,
 'Fare': 15,
 'Embarked': 'S',
 'Title': 'Mr',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 2,
 'IsAlone': 0,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Small',
 'Embarked_C': 0,
 'Embarked_Q': 0,
 'Embarked_S': 1,
 'Title_Master': 0,
 'Title_Miss': 0,
 'Title_Mr': 1,
 'Title_Mrs': 0,
 'Title_Other': 0}

In [0]:
second_passenger["AgeGroup_Child"] = int(second_passenger["AgeGroup"]== "Child")
second_passenger["AgeGroup_Teen"] = int(second_passenger["AgeGroup"]== "Teen")
second_passenger["AgeGroup_Adult"] = int(second_passenger["AgeGroup"]== "Adult")
second_passenger["AgeGroup_Senior"]= int(second_passenger["AgeGroup"]== "Senior")

second_passenger

{'Pclass': 3,
 'Sex': 0,
 'Age': 30,
 'SibSp': 1,
 'Parch': 0,
 'Fare': 15,
 'Embarked': 'S',
 'Title': 'Mr',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 2,
 'IsAlone': 0,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Small',
 'Embarked_C': 0,
 'Embarked_Q': 0,
 'Embarked_S': 1,
 'Title_Master': 0,
 'Title_Miss': 0,
 'Title_Mr': 1,
 'Title_Mrs': 0,
 'Title_Other': 0,
 'AgeGroup_Child': 0,
 'AgeGroup_Teen': 0,
 'AgeGroup_Adult': 1,
 'AgeGroup_Senior': 0}

In [0]:
second_passenger["FamilySizeGroup_Alone"] = int(second_passenger["FamilySizeGroup"] == "Alone")
second_passenger["FamilySizeGroup_Small"] = int(second_passenger["FamilySizeGroup"] == "Small")
second_passenger["FamilySizeGroup_Medium"] = int(second_passenger["FamilySizeGroup"] == "Medium")
second_passenger["FamilySizeGroup_Large"] = int(second_passenger["FamilySizeGroup"] == "Large")

second_passenger

{'Pclass': 3,
 'Sex': 0,
 'Age': 30,
 'SibSp': 1,
 'Parch': 0,
 'Fare': 15,
 'Embarked': 'S',
 'Title': 'Mr',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 2,
 'IsAlone': 0,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Small',
 'Embarked_C': 0,
 'Embarked_Q': 0,
 'Embarked_S': 1,
 'Title_Master': 0,
 'Title_Miss': 0,
 'Title_Mr': 1,
 'Title_Mrs': 0,
 'Title_Other': 0,
 'AgeGroup_Child': 0,
 'AgeGroup_Teen': 0,
 'AgeGroup_Adult': 1,
 'AgeGroup_Senior': 0,
 'FamilySizeGroup_Alone': 0,
 'FamilySizeGroup_Small': 1,
 'FamilySizeGroup_Medium': 0,
 'FamilySizeGroup_Large': 0}

In [0]:
cabin_decks = ["A", "B", "C", "D", "E", "F", "G", "T", "Unknown"]
for deck in cabin_decks:
    second_passenger[f"Cabin_Deck_{deck}"] = int(
        second_passenger["Cabin_Deck"]== deck
    )

second_passenger

{'Pclass': 3,
 'Sex': 0,
 'Age': 30,
 'SibSp': 1,
 'Parch': 0,
 'Fare': 15,
 'Embarked': 'S',
 'Title': 'Mr',
 'Cabin_Deck': 'Unknown',
 'FamilySize': 2,
 'IsAlone': 0,
 'AgeGroup': 'Adult',
 'FamilySizeGroup': 'Small',
 'Embarked_C': 0,
 'Embarked_Q': 0,
 'Embarked_S': 1,
 'Title_Master': 0,
 'Title_Miss': 0,
 'Title_Mr': 1,
 'Title_Mrs': 0,
 'Title_Other': 0,
 'AgeGroup_Child': 0,
 'AgeGroup_Teen': 0,
 'AgeGroup_Adult': 1,
 'AgeGroup_Senior': 0,
 'FamilySizeGroup_Alone': 0,
 'FamilySizeGroup_Small': 1,
 'FamilySizeGroup_Medium': 0,
 'FamilySizeGroup_Large': 0,
 'Cabin_Deck_A': 0,
 'Cabin_Deck_B': 0,
 'Cabin_Deck_C': 0,
 'Cabin_Deck_D': 0,
 'Cabin_Deck_E': 0,
 'Cabin_Deck_F': 0,
 'Cabin_Deck_G': 0,
 'Cabin_Deck_T': 0,
 'Cabin_Deck_Unknown': 1}

In [0]:
second_passenger_df = pd.DataFrame([second_passenger])
second_passenger_df

   Pclass  Sex  Age  ...  Cabin_Deck_G  Cabin_Deck_T  Cabin_Deck_Unknown
0       3    0   30  ...             0             0                   1

[1 rows x 38 columns]

In [0]:
second_passenger_df = second_passenger_df[X.columns]
second_passenger_df.shape

(1, 33)

In [0]:
second_prediction = model.predict(second_passenger_df)
second_prediction

array([0])

In [0]:
second_probability = model.predict_proba(second_passenger_df)
second_probability

array([[0.93647726, 0.06352274]])

## Conclusion

The trained Logistic Regression model was used to predict the survival of new passengers.

### Probability Interpretation — Passenger 1

The probability output is: `[[0.08436211, 0.91563789]]`

- Probability of **not surviving (0)**: **8.44%**
- Probability of **surviving (1)**: **91.56%**

The higher probability is for class `1`, which matches the prediction.

### Probability Interpretation — Passenger 2

The probability output is: `[[0.93647726, 0.06352274]]`

- Probability of **not surviving (0)**: **93.65%**
- Probability of **surviving (1)**: **6.35%**

The higher probability is for class `0`, which matches the prediction.

The complete prediction workflow was demonstrated for individual passenger records: passenger information → derived features → encoding → model feature schema → prediction → class probability.